<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuactionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = DB::table('menu_actions')->get();
        $num = count($list);
        if($num == 0){
            //DB::table('menu_actions')->delete();
            DB::table('menu_actions')->insert(
                array (
                    0 => array (
                        'id' => 1,
                        'menu_id' => 1,
                        'action_name' => '系统设置',
                        'action_route' => 'javascript:void(0);',
                        'parent_id' => 0,
                        'child_ids' => '',
                        'role_ids' => '1',
                        'status' => 'yes',
                        'sort_order' => 30,
                        'sys_mark' => 'sys',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    1 => array (
                        'id' => 2,
                        'menu_id' => 1,
                        'action_name' => '用户管理',
                        'action_route' => '/agent/users',
                        'parent_id' => 1,
                        'child_ids' => '',
                        'role_ids' => '1',
                        'status' => 'yes',
                        'sort_order' => 1,
                        'sys_mark' => 'sys',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    2 => array (
                        'id' => 3,
                        'menu_id' => 1,
                        'action_name' => '角色管理',
                        'action_route' => '/agent/roles',
                        'parent_id' => 1,
                        'child_ids' => '',
                        'role_ids' => '1',
                        'status' => 'yes',
                        'sort_order' => 2,
                        'sys_mark' => 'sys',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    3 => array (
                        'id' => 4,
                        'menu_id' => 1,
                        'action_name' => '权限管理',
                        'action_route' => '/agent/rolelists',
                        'parent_id' => 1,
                        'child_ids' => '',
                        'role_ids' => '1',
                        'status' => 'yes',
                        'sort_order' => 3,
                        'sys_mark' => 'sys',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    4 => array (
                        'id' => 5,
                        'menu_id' => 1,
                        'action_name' => '菜单位置',
                        'action_route' => '/agent/menus',
                        'parent_id' => 1,
                        'child_ids' => '',
                        'role_ids' => '1',
                        'status' => 'yes',
                        'sort_order' => 4,
                        'sys_mark' => 'sys',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    5 => array (
                        'id' => 6,
                        'menu_id' => 1,
                        'action_name' => '菜单路由',
                        'action_route' => '/agent/menuactions',
                        'parent_id' => 1,
                        'child_ids' => '',
                        'role_ids' => '1',
                        'status' => 'yes',
                        'sort_order' => 5,
                        'sys_mark' => 'sys',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    6 => array (
                        'id' => 7,
                        'menu_id' => 1,
                        'action_name' => '基础设置',
                        'action_route' => 'javascript:void(0);',
                        'parent_id' => 0,
                        'child_ids' => '',
                        'role_ids' => '1,2,3',
                        'status' => 'yes',
                        'sort_order' => 30,
                        'sys_mark' => '',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    7 => array (
                        'id' => 8,
                        'menu_id' => 1,
                        'action_name' => '角色权限',
                        'action_route' => '/agent/rolerelations',
                        'parent_id' => 7,
                        'child_ids' => '',
                        'role_ids' => '1,2,3',
                        'status' => 'yes',
                        'sort_order' => 1,
                        'sys_mark' => '',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    8 => array (
                        'id' => 9,
                        'menu_id' => 1,
                        'action_name' => '部门人员',
                        'action_route' => '/agent/department/index',
                        'parent_id' => 7,
                        'child_ids' => '',
                        'role_ids' => '1,2,3',
                        'status' => 'yes',
                        'sort_order' => 2,
                        'sys_mark' => '',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    9 => array (
                        'id' => 10,
                        'menu_id' => 1,
                        'action_name' => '客户授权',
                        'action_route' => '/agent/authorizations',
                        'parent_id' => 7,
                        'child_ids' => '',
                        'role_ids' => '1,2,3',
                        'status' => 'yes',
                        'sort_order' => 3,
                        'sys_mark' => '',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    10 => array (
                        'id' => 11,
                        'menu_id' => 1,
                        'action_name' => '客户信息',
                        'action_route' => 'javascript:void(0);',
                        'parent_id' => 0,
                        'child_ids' => '',
                        'role_ids' => '1,2,3',
                        'status' => 'yes',
                        'sort_order' => 29,
                        'sys_mark' => '',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    11 => array (
                        'id' => 12,
                        'menu_id' => 1,
                        'action_name' => '客户列表',
                        'action_route' => '/agent/companies',
                        'parent_id' => 11,
                        'child_ids' => '',
                        'role_ids' => '1,2,3',
                        'status' => 'yes',
                        'sort_order' => 1,
                        'sys_mark' => '',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    12 => array (
                        'id' => 13,
                        'menu_id' => 1,
                        'action_name' => '停用列表',
                        'action_route' => '/agent/companies/freezlist',
                        'parent_id' => 11,
                        'child_ids' => '',
                        'role_ids' => '1,2,3',
                        'status' => 'yes',
                        'sort_order' => 2,
                        'sys_mark' => '',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    ),
                    13 => array (
                        'id' => 14,
                        'menu_id' => 1,
                        'action_name' => '系统通知',
                        'action_route' => 'javascript:void(0);',
                        'parent_id' => 0,
                        'child_ids' => '',
                        'role_ids' => '1,2,3',
                        'status' => 'yes',
                        'sort_order' => 28,
                        'sys_mark' => '',
                        'created_at' => '2018-05-30 15:00:00',
                        'updated_at' => '2018-05-30 15:00:00',
                    )
                )
            );

        }

    }
}
