<?php
return
    [
        [
            'number' => '1001',
            'name' => '库存现金',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1002',
            'name' => '银行存款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1012',
            'name' => '其他货币资金',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => [
                [
                    'number' => '101201',
                    'name' => '外埠存款',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '101202',
                    'name' => '银行本票存款',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '101203',
                    'name' => '银行汇票存款',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '101204',
                    'name' => '信用卡存款',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '101205',
                    'name' => '信用证保证金存款',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '101206',
                    'name' => '存出投资款',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1101',
            'name' => '交易性金融资产',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => [
                [
                    'number' => '110101',
                    'name' => '本金',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => [
                        [
                            'number' => '11010101',
                            'name' => '股票',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                        [
                            'number' => '11010102',
                            'name' => '债券',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                        [
                            'number' => '11010103',
                            'name' => '基金',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                        [
                            'number' => '11010104',
                            'name' => '权证',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                        [
                            'number' => '11010199',
                            'name' => '其他',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                    ],
                ],
                [
                    'number' => '110102',
                    'name' => '公允价值变动',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => [
                        [
                            'number' => '11010201',
                            'name' => '股票',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                        [
                            'number' => '11010202',
                            'name' => '债券',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                        [
                            'number' => '11010203',
                            'name' => '基金',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                        [
                            'number' => '11010204',
                            'name' => '权证',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                        [
                            'number' => '11010299',
                            'name' => '其他',
                            'balance_direction' => '借',
                            'type' => '流动资产',
                            'items' => '',
                        ],
                    ],
                ],
            ],
        ],
        [
            'number' => '1121',
            'name' => '应收票据',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1122',
            'name' => '应收账款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1123',
            'name' => '预付账款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1131',
            'name' => '应收股利',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1132',
            'name' => '应收利息',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1221',
            'name' => '其他应收款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1231',
            'name' => '坏账准备',
            'balance_direction' => '贷',
            'type' => '流动资产',
            'items' => [
                [
                    'number' => '123101',
                    'name' => '应收账款坏账准备',
                    'balance_direction' => '贷',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '123102',
                    'name' => '其他应收款坏账准备',
                    'balance_direction' => '贷',
                    'type' => '流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1321',
            'name' => '受托代销商品',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1401',
            'name' => '材料采购',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1402',
            'name' => '在途物资',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1403',
            'name' => '原材料',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1404',
            'name' => '材料成本差异',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1405',
            'name' => '库存商品',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1406',
            'name' => '发出商品',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1407',
            'name' => '商品进销差价',
            'balance_direction' => '贷',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1408',
            'name' => '委托加工物资',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1411',
            'name' => '周转材料',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1471',
            'name' => '存货跌价准备',
            'balance_direction' => '贷',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1501',
            'name' => '持有至到期投资',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => [
                [
                    'number' => '150101',
                    'name' => '投资成本',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '150102',
                    'name' => '溢折价',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '150103',
                    'name' => '应计利息',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1502',
            'name' => '持有至到期投资减值准备',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1503',
            'name' => '可供出售金融资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1511',
            'name' => '长期股权投资',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => [
                [
                    'number' => '151101',
                    'name' => '投资成本',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '151102',
                    'name' => '损益调整',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '151103',
                    'name' => '所有者权益其他变动',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1512',
            'name' => '长期股权投资减值准备',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1521',
            'name' => '投资性房地产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => [
                [
                    'number' => '152101',
                    'name' => '成本',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '152102',
                    'name' => '公允价值变动',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1531',
            'name' => '长期应收款',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1532',
            'name' => '未实现融资收益',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1601',
            'name' => '固定资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1602',
            'name' => '累计折旧',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1603',
            'name' => '固定资产减值准备',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1604',
            'name' => '在建工程',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => [
                [
                    'number' => '160401',
                    'name' => '建筑工程',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160402',
                    'name' => '安装工程',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160403',
                    'name' => '在安装设备',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160404',
                    'name' => '待摊支出',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1605',
            'name' => '工程物资',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => [
                [
                    'number' => '160501',
                    'name' => '专用材料',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160502',
                    'name' => '专用设备',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160503',
                    'name' => '预付大型设备款',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160504',
                    'name' => '为生产准备的工具及器具',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1606',
            'name' => '固定资产清理',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1701',
            'name' => '无形资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1702',
            'name' => '累计摊销',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1703',
            'name' => '无形资产减值准备',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1711',
            'name' => '商誉',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1801',
            'name' => '长期待摊费用',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1811',
            'name' => '递延所得税资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1901',
            'name' => '待处理财产损溢',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '2001',
            'name' => '短期借款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2101',
            'name' => '交易性金融负债',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => [
                [
                    'number' => '210101',
                    'name' => '本金',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '210102',
                    'name' => '公允价值变动',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2201',
            'name' => '应付票据',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2202',
            'name' => '应付账款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2203',
            'name' => '预收账款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2211',
            'name' => '应付职工薪酬',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => [
                [
                    'number' => '221101',
                    'name' => '工资',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '221102',
                    'name' => '职工福利',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '221103',
                    'name' => '社会保险费',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '221104',
                    'name' => '住房公积金',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '221105',
                    'name' => '工会经费',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '221106',
                    'name' => '职工教育经费',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '221107',
                    'name' => '解除职工劳动关系补偿',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2221',
            'name' => '应交税费',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => [
                [
                    'number' => '222101',
                    'name' => '应交增值税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => [
                        [
                            'number' => '22210101',
                            'name' => '进项税额',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210102',
                            'name' => '已交税金',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210103',
                            'name' => '减免税款',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210104',
                            'name' => '出口抵减内销产品应纳税额',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210105',
                            'name' => '转出未交增值税',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210106',
                            'name' => '销项税额',
                            'balance_direction' => '贷',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210107',
                            'name' => '出口退税',
                            'balance_direction' => '贷',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210108',
                            'name' => '进项税额转出',
                            'balance_direction' => '贷',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210109',
                            'name' => '转出多交增值税',
                            'balance_direction' => '贷',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                    ],
                ],
                [
                    'number' => '222102',
                    'name' => '未交增值税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222103',
                    'name' => '应交营业税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222104',
                    'name' => '应交消费税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222105',
                    'name' => '应交资源税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222106',
                    'name' => '应交所得税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222107',
                    'name' => '应交土地增值税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222108',
                    'name' => '应交城市维护建设税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222109',
                    'name' => '应交房产税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222110',
                    'name' => '应交土地使用税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222111',
                    'name' => '应交车船使用税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222112',
                    'name' => '应交个人所得税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222113',
                    'name' => '教育费附加',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222114',
                    'name' => '地方教育费附加',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2231',
            'name' => '应付股利',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2232',
            'name' => '应付利息',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2241',
            'name' => '其他应付款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2314',
            'name' => '受托代销商品款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2401',
            'name' => '递延收益',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2501',
            'name' => '长期借款',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => [
                [
                    'number' => '250101',
                    'name' => '本金',
                    'balance_direction' => '贷',
                    'type' => '非流动负债',
                    'items' => '',
                ],
                [
                    'number' => '250102',
                    'name' => '利息调整',
                    'balance_direction' => '贷',
                    'type' => '非流动负债',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2502',
            'name' => '应付债券',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => [
                [
                    'number' => '250201',
                    'name' => '债券面值',
                    'balance_direction' => '贷',
                    'type' => '非流动负债',
                    'items' => '',
                ],
                [
                    'number' => '250202',
                    'name' => '利息调整',
                    'balance_direction' => '贷',
                    'type' => '非流动负债',
                    'items' => '',
                ],
                [
                    'number' => '250203',
                    'name' => '应计利息',
                    'balance_direction' => '贷',
                    'type' => '非流动负债',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2701',
            'name' => '长期应付款',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '2702',
            'name' => '未确认融资费用',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '2711',
            'name' => '专项应付款',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '2801',
            'name' => '预计负债',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '2901',
            'name' => '递延所得税负债',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '3101',
            'name' => '衍生工具',
            'balance_direction' => '借',
            'type' => '共同',
            'items' => '',
        ],
        [
            'number' => '3201',
            'name' => '套期工具',
            'balance_direction' => '借',
            'type' => '共同',
            'items' => '',
        ],
        [
            'number' => '3202',
            'name' => '被套期项目',
            'balance_direction' => '借',
            'type' => '共同',
            'items' => '',
        ],
        [
            'number' => '4001',
            'name' => '实收资本',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => '',
        ],
        [
            'number' => '4002',
            'name' => '资本公积',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => [
                [
                    'number' => '400201',
                    'name' => '资本溢价',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '400202',
                    'name' => '股本溢价',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '400203',
                    'name' => '其他资本公积',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '4101',
            'name' => '盈余公积',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => [
                [
                    'number' => '410101',
                    'name' => '法定盈余公积',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410102',
                    'name' => '任意盈余公积',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410103',
                    'name' => '法定公益金',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410104',
                    'name' => '储备基金',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410105',
                    'name' => '企业发展基金',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410106',
                    'name' => '利润归还投资',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '4103',
            'name' => '本年利润',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => '',
        ],
        [
            'number' => '4104',
            'name' => '利润分配',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => [
                [
                    'number' => '410401',
                    'name' => '提取法定盈余公积',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410402',
                    'name' => '提取任意盈余公积',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410403',
                    'name' => '提取法定公益金',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410404',
                    'name' => '应付现金股利或利润',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410405',
                    'name' => '转作股本的利润',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410406',
                    'name' => '盈余公积补亏',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410407',
                    'name' => '提取储备基金',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410408',
                    'name' => '提取企业发展基金',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410409',
                    'name' => '提取职工奖励及福利基金',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410410',
                    'name' => '利润归还投资',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '410411',
                    'name' => '未分配利润',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '4201',
            'name' => '库存股',
            'balance_direction' => '借',
            'type' => '所有者权益',
            'items' => '',
        ],
        [
            'number' => '5001',
            'name' => '生产成本',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => [
                [
                    'number' => '500101',
                    'name' => '基本生产成本',
                    'balance_direction' => '借',
                    'type' => '成本',
                    'items' => '',
                ],
                [
                    'number' => '500102',
                    'name' => '辅助生产成本',
                    'balance_direction' => '借',
                    'type' => '成本',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5101',
            'name' => '制造费用',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => '',
        ],
        [
            'number' => '5201',
            'name' => '劳务成本',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => '',
        ],
        [
            'number' => '5301',
            'name' => '研发支出',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => [
                [
                    'number' => '530101',
                    'name' => '费用化支出',
                    'balance_direction' => '借',
                    'type' => '成本',
                    'items' => '',
                ],
                [
                    'number' => '530102',
                    'name' => '资本化支出',
                    'balance_direction' => '借',
                    'type' => '成本',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '6001',
            'name' => '主营业务收入',
            'balance_direction' => '贷',
            'type' => '营业收入',
            'items' => '',
        ],
        [
            'number' => '6051',
            'name' => '其他业务收入',
            'balance_direction' => '贷',
            'type' => '营业收入',
            'items' => '',
        ],
        [
            'number' => '6101',
            'name' => '公允价值变动损益',
            'balance_direction' => '贷',
            'type' => '其他收益',
            'items' => '',
        ],
        [
            'number' => '6111',
            'name' => '投资收益',
            'balance_direction' => '贷',
            'type' => '其他收益',
            'items' => '',
        ],
        [
            'number' => '6301',
            'name' => '营业外收入',
            'balance_direction' => '贷',
            'type' => '其他收益',
            'items' => '',
        ],
        [
            'number' => '6401',
            'name' => '主营业务成本',
            'balance_direction' => '借',
            'type' => '营业成本及税金',
            'items' => '',
        ],
        [
            'number' => '6402',
            'name' => '其他业务成本',
            'balance_direction' => '借',
            'type' => '营业成本及税金',
            'items' => '',
        ],
        [
            'number' => '6403',
            'name' => '营业税金及附加',
            'balance_direction' => '借',
            'type' => '营业成本及税金',
            'items' => '',
        ],
        [
            'number' => '6601',
            'name' => '销售费用',
            'balance_direction' => '借',
            'type' => '期间费用',
            'items' => [
                [
                    'number' => '660101',
                    'name' => '工资',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660102',
                    'name' => '福利费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660103',
                    'name' => '办公用品费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660104',
                    'name' => '业务招待费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660105',
                    'name' => '广告和业务宣传费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660106',
                    'name' => '差旅费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660199',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '6602',
            'name' => '管理费用',
            'balance_direction' => '借',
            'type' => '期间费用',
            'items' => [
                [
                    'number' => '660201',
                    'name' => '工资',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660202',
                    'name' => '福利费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660203',
                    'name' => '办公用品费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660204',
                    'name' => '业务招待费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660205',
                    'name' => '交通费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660206',
                    'name' => '运杂费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660207',
                    'name' => '差旅费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660208',
                    'name' => '通讯费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660209',
                    'name' => '修理费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660210',
                    'name' => '房租',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660211',
                    'name' => '水电管理费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660212',
                    'name' => '折旧费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660213',
                    'name' => '保险费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660214',
                    'name' => '公积金',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660299',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '6603',
            'name' => '财务费用',
            'balance_direction' => '借',
            'type' => '期间费用',
            'items' => [
                [
                    'number' => '660301',
                    'name' => '汇兑损益',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660302',
                    'name' => '利息',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660303',
                    'name' => '手续费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '660399',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '6701',
            'name' => '资产减值损失',
            'balance_direction' => '借',
            'type' => '其他损失',
            'items' => '',
        ],
        [
            'number' => '6711',
            'name' => '营业外支出',
            'balance_direction' => '借',
            'type' => '其他损失',
            'items' => '',
        ],
        [
            'number' => '6801',
            'name' => '所得税',
            'balance_direction' => '借',
            'type' => '所得税',
            'items' => [
                [
                    'number' => '680101',
                    'name' => '当期所得税费用',
                    'balance_direction' => '借',
                    'type' => '所得税',
                    'items' => '',
                ],
                [
                    'number' => '680102',
                    'name' => '递延所得税费用',
                    'balance_direction' => '借',
                    'type' => '所得税',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '6901',
            'name' => '以前年度损益调整',
            'balance_direction' => '借',
            'type' => '以前年度损益调整',
            'items' => '',
        ],
    ];