<?php
return
    [
        [
            'number' => '1001',
            'name' => '库存现金',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1002',
            'name' => '银行存款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1012',
            'name' => '其他货币资金',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1101',
            'name' => '短期投资',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => [
                [
                    'number' => '110101',
                    'name' => '股票',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '110102',
                    'name' => '债券',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '110103',
                    'name' => '基金',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
                [
                    'number' => '110110',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1121',
            'name' => '应收票据',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1122',
            'name' => '应收账款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1123',
            'name' => '预付账款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1131',
            'name' => '应收股利',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1132',
            'name' => '应收利息',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1221',
            'name' => '其他应收款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1401',
            'name' => '材料采购',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1402',
            'name' => '在途物资',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1403',
            'name' => '原材料',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1404',
            'name' => '材料成本差异',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1405',
            'name' => '库存商品',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1407',
            'name' => '商品进销差价',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1408',
            'name' => '委托加工物资',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1411',
            'name' => '周转材料',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1421',
            'name' => '消耗性生物资产',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1501',
            'name' => '长期债券投资',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => [
                [
                    'number' => '150101',
                    'name' => '债券投资',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '150102',
                    'name' => '其他债权投资',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1511',
            'name' => '长期股权投资',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => [
                [
                    'number' => '151101',
                    'name' => '股票投资',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '151102',
                    'name' => '其他股权投资',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1601',
            'name' => '固定资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1602',
            'name' => '累计折旧',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1604',
            'name' => '在建工程',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => [
                [
                    'number' => '160401',
                    'name' => '建筑工程',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160402',
                    'name' => '安装工程',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160403',
                    'name' => '技术改造工程',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
                [
                    'number' => '160404',
                    'name' => '其他支出',
                    'balance_direction' => '借',
                    'type' => '非流动资产',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '1605',
            'name' => '工程物资',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1606',
            'name' => '固定资产清理',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1621',
            'name' => '生产性生物资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1622',
            'name' => '生产性生物资产累计折旧',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1701',
            'name' => '无形资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1702',
            'name' => '累计摊销',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1801',
            'name' => '长期待摊费用',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1901',
            'name' => '待处理财产损溢',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '2001',
            'name' => '短期借款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2201',
            'name' => '应付票据',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2202',
            'name' => '应付账款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2203',
            'name' => '预收账款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2211',
            'name' => '应付职工薪酬',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2221',
            'name' => '应交税费',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => [
                [
                    'number' => '222101',
                    'name' => '应交增值税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => [
                        [
                            'number' => '22210101',
                            'name' => '进项税额',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210102',
                            'name' => '已交税金',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210103',
                            'name' => '减免税款',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210104',
                            'name' => '出口抵减内销产品应纳税额',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210105',
                            'name' => '转出未交增值税',
                            'balance_direction' => '借',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210106',
                            'name' => '销项税额',
                            'balance_direction' => '贷',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210107',
                            'name' => '出口退税',
                            'balance_direction' => '贷',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210108',
                            'name' => '进项税额转出',
                            'balance_direction' => '贷',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                        [
                            'number' => '22210109',
                            'name' => '转出多交增值税',
                            'balance_direction' => '贷',
                            'type' => '流动负债',
                            'items' => '',
                        ],
                    ],
                ],
                [
                    'number' => '222102',
                    'name' => '未交增值税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222103',
                    'name' => '应交营业税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222104',
                    'name' => '应交消费税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222105',
                    'name' => '应交资源税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222106',
                    'name' => '应交所得税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222107',
                    'name' => '应交土地增值税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222108',
                    'name' => '应交城市维护建设税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222109',
                    'name' => '应交房产税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222110',
                    'name' => '应交土地使用税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222111',
                    'name' => '应交车船使用税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222112',
                    'name' => '应交个人所得税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222113',
                    'name' => '教育费附加',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '222114',
                    'name' => '地方教育费附加',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2231',
            'name' => '应付利息',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2232',
            'name' => '应付利润',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2241',
            'name' => '其他应付款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2401',
            'name' => '递延收益',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2501',
            'name' => '长期借款',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '2701',
            'name' => '长期应付款',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '3001',
            'name' => '实收资本',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => '',
        ],
        [
            'number' => '3002',
            'name' => '资本公积',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => [
                [
                    'number' => '300201',
                    'name' => '资本溢价',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '300202',
                    'name' => '接受捐赠非现金资产准备',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '300206',
                    'name' => '外币资本折算差额',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '300207',
                    'name' => '其他资本公积',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '3101',
            'name' => '盈余公积',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => [
                [
                    'number' => '310101',
                    'name' => '法定盈余公积',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '310102',
                    'name' => '任意盈余公积',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '310103',
                    'name' => '法定公益金',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '3103',
            'name' => '本年利润',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => '',
        ],
        [
            'number' => '3104',
            'name' => '利润分配',
            'balance_direction' => '贷',
            'type' => '所有者权益',
            'items' => [
                [
                    'number' => '310401',
                    'name' => '其他转入',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '310402',
                    'name' => '提取法定盈余公积',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '310403',
                    'name' => '提取法定公益金',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '310409',
                    'name' => '提取任意盈余公积',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '310410',
                    'name' => '应付利润',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '310411',
                    'name' => '转作资本的利润',
                    'balance_direction' => '借',
                    'type' => '所有者权益',
                    'items' => '',
                ],
                [
                    'number' => '310415',
                    'name' => '未分配利润',
                    'balance_direction' => '贷',
                    'type' => '所有者权益',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '4001',
            'name' => '生产成本',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => [
                [
                    'number' => '400101',
                    'name' => '基本生产成本',
                    'balance_direction' => '借',
                    'type' => '成本',
                    'items' => '',
                ],
                [
                    'number' => '400102',
                    'name' => '辅助生产成本',
                    'balance_direction' => '借',
                    'type' => '成本',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '4101',
            'name' => '制造费用',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => '',
        ],
        [
            'number' => '4301',
            'name' => '研发支出',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => '',
        ],
        [
            'number' => '4401',
            'name' => '工程施工',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => '',
        ],
        [
            'number' => '4403',
            'name' => '机械作业',
            'balance_direction' => '借',
            'type' => '成本',
            'items' => '',
        ],
        [
            'number' => '5001',
            'name' => '主营业务收入',
            'balance_direction' => '贷',
            'type' => '营业收入',
            'items' => '',
        ],
        [
            'number' => '5051',
            'name' => '其他业务收入',
            'balance_direction' => '贷',
            'type' => '其他收益',
            'items' => '',
        ],
        [
            'number' => '5111',
            'name' => '投资收益',
            'balance_direction' => '贷',
            'type' => '其他收益',
            'items' => '',
        ],
        [
            'number' => '5301',
            'name' => '营业外收入',
            'balance_direction' => '贷',
            'type' => '其他收益',
            'items' => [
                [
                    'number' => '530101',
                    'name' => '非流动资产处置净收益',
                    'balance_direction' => '贷',
                    'type' => '其他收益',
                    'items' => '',
                ],
                [
                    'number' => '530102',
                    'name' => '政府补助',
                    'balance_direction' => '贷',
                    'type' => '其他收益',
                    'items' => '',
                ],
                [
                    'number' => '530103',
                    'name' => '捐赠收益',
                    'balance_direction' => '贷',
                    'type' => '其他收益',
                    'items' => '',
                ],
                [
                    'number' => '530104',
                    'name' => '盘盈收益',
                    'balance_direction' => '贷',
                    'type' => '其他收益',
                    'items' => '',
                ],
                [
                    'number' => '530105',
                    'name' => '其他',
                    'balance_direction' => '贷',
                    'type' => '其他收益',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5401',
            'name' => '主营业务成本',
            'balance_direction' => '借',
            'type' => '营业成本及税金',
            'items' => '',
        ],
        [
            'number' => '5402',
            'name' => '其他业务成本',
            'balance_direction' => '借',
            'type' => '其他损失',
            'items' => '',
        ],
        [
            'number' => '5403',
            'name' => '营业税金及附加',
            'balance_direction' => '借',
            'type' => '营业成本及税金',
            'items' => '',
        ],
        [
            'number' => '5501',
            'name' => '营业费用',
            'balance_direction' => '借',
            'type' => '期间费用',
            'items' => [
                [
                    'number' => '550101',
                    'name' => '办公费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5601',
            'name' => '销售费用',
            'balance_direction' => '借',
            'type' => '期间费用',
            'items' => [
                [
                    'number' => '560101',
                    'name' => '工资',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560102',
                    'name' => '福利费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560103',
                    'name' => '办公用品费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560104',
                    'name' => '业务招待费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560105',
                    'name' => '广告和业务宣传费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560106',
                    'name' => '差旅费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560199',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5602',
            'name' => '管理费用',
            'balance_direction' => '借',
            'type' => '期间费用',
            'items' => [
                [
                    'number' => '560201',
                    'name' => '工资',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560202',
                    'name' => '福利费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560203',
                    'name' => '办公用品费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560204',
                    'name' => '业务招待费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560205',
                    'name' => '交通费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560206',
                    'name' => '运杂费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560207',
                    'name' => '差旅费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560208',
                    'name' => '通讯费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560209',
                    'name' => '修理费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560210',
                    'name' => '房租',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560211',
                    'name' => '水电管理费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560212',
                    'name' => '折旧费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560213',
                    'name' => '保险费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560214',
                    'name' => '公积金',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560299',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5603',
            'name' => '财务费用',
            'balance_direction' => '借',
            'type' => '期间费用',
            'items' => [
                [
                    'number' => '560301',
                    'name' => '汇兑损益',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560302',
                    'name' => '利息',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560303',
                    'name' => '手续费',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
                [
                    'number' => '560399',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '期间费用',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5711',
            'name' => '营业外支出',
            'balance_direction' => '借',
            'type' => '其他损失',
            'items' => [
                [
                    'number' => '571101',
                    'name' => '存货盘亏毁损',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571102',
                    'name' => '非流动资产处置净损失',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571103',
                    'name' => '坏账损失',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571104',
                    'name' => '无法收回的长期债券投资损失',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571105',
                    'name' => '无法收回的长期股权投资损失',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571106',
                    'name' => '自然灾害等不可抗力造成的损失',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571107',
                    'name' => '税收滞纳金',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571108',
                    'name' => '罚金、罚款',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571109',
                    'name' => '捐赠支出',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
                [
                    'number' => '571110',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '其他损失',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5801',
            'name' => '所得税费用',
            'balance_direction' => '借',
            'type' => '所得税',
            'items' => '',
        ],
        [
            'number' => '6000',
            'name' => '以前年度损益调整',
            'balance_direction' => '借',
            'type' => '以前年度损益调整',
            'items' => '',
        ],
    ];