<?php
return
    [
        [
            'number' => '1001',
            'name' => '现金',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1002',
            'name' => '银行存款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1009',
            'name' => '其他货币资金',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1101',
            'name' => '短期投资',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1102',
            'name' => '短期投资跌价准备',
            'balance_direction' => '贷',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1111',
            'name' => '应收票据',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1121',
            'name' => '应收账款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1122',
            'name' => '其他应收款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1131',
            'name' => '坏账准备',
            'balance_direction' => '贷',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1141',
            'name' => '预付账款',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1201',
            'name' => '存货',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1202',
            'name' => '存货跌价准备',
            'balance_direction' => '贷',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1301',
            'name' => '待摊费用',
            'balance_direction' => '借',
            'type' => '流动资产',
            'items' => '',
        ],
        [
            'number' => '1401',
            'name' => '长期股权投资',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1402',
            'name' => '长期债权投资',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1421',
            'name' => '长期投资减值准备',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1501',
            'name' => '固定资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1502',
            'name' => '累计折旧',
            'balance_direction' => '贷',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1505',
            'name' => '在建工程',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1506',
            'name' => '文物文化资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1509',
            'name' => '固定资产清理',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1601',
            'name' => '无形资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '1701',
            'name' => '受托代理资产',
            'balance_direction' => '借',
            'type' => '非流动资产',
            'items' => '',
        ],
        [
            'number' => '2101',
            'name' => '短期借款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2201',
            'name' => '应付票据',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2202',
            'name' => '应付账款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2203',
            'name' => '预收账款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2204',
            'name' => '应付工资',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2206',
            'name' => '应交税金',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => [
                [
                    'number' => '220601',
                    'name' => '营业税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '220602',
                    'name' => '增值税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '220603',
                    'name' => '所得税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '220604',
                    'name' => '房产税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
                [
                    'number' => '220605',
                    'name' => '个人所得税',
                    'balance_direction' => '贷',
                    'type' => '流动负债',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2209',
            'name' => '其他应付款',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2301',
            'name' => '预提费用',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2401',
            'name' => '预计负债',
            'balance_direction' => '贷',
            'type' => '流动负债',
            'items' => '',
        ],
        [
            'number' => '2501',
            'name' => '长期借款',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '2502',
            'name' => '长期应付款',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '2601',
            'name' => '受托代理负债',
            'balance_direction' => '贷',
            'type' => '非流动负债',
            'items' => '',
        ],
        [
            'number' => '3101',
            'name' => '非限定性净资产',
            'balance_direction' => '贷',
            'type' => '净资产',
            'items' => '',
        ],
        [
            'number' => '3102',
            'name' => '限定性净资产',
            'balance_direction' => '贷',
            'type' => '净资产',
            'items' => '',
        ],
        [
            'number' => '4101',
            'name' => '捐赠收入',
            'balance_direction' => '贷',
            'type' => '收入',
            'items' => '',
        ],
        [
            'number' => '4201',
            'name' => '会费收入',
            'balance_direction' => '贷',
            'type' => '收入',
            'items' => [
                [
                    'number' => '420101',
                    'name' => '团体会费',
                    'balance_direction' => '贷',
                    'type' => '收入',
                    'items' => '',
                ],
                [
                    'number' => '420102',
                    'name' => '个人会费',
                    'balance_direction' => '贷',
                    'type' => '收入',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '4301',
            'name' => '提供服务收入',
            'balance_direction' => '贷',
            'type' => '收入',
            'items' => [
                [
                    'number' => '430101',
                    'name' => '学杂费收入',
                    'balance_direction' => '贷',
                    'type' => '收入',
                    'items' => '',
                ],
                [
                    'number' => '430102',
                    'name' => '医疗收入',
                    'balance_direction' => '贷',
                    'type' => '收入',
                    'items' => '',
                ],
                [
                    'number' => '430103',
                    'name' => '培训收入',
                    'balance_direction' => '贷',
                    'type' => '收入',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '4401',
            'name' => '政府补助收入',
            'balance_direction' => '贷',
            'type' => '收入',
            'items' => '',
        ],
        [
            'number' => '4501',
            'name' => '商品销售收入',
            'balance_direction' => '贷',
            'type' => '收入',
            'items' => '',
        ],
        [
            'number' => '4601',
            'name' => '投资收益',
            'balance_direction' => '贷',
            'type' => '收入',
            'items' => '',
        ],
        [
            'number' => '4901',
            'name' => '其他收入',
            'balance_direction' => '贷',
            'type' => '收入',
            'items' => '',
        ],
        [
            'number' => '5101',
            'name' => '业务活动成本',
            'balance_direction' => '借',
            'type' => '支出',
            'items' => '',
        ],
        [
            'number' => '5201',
            'name' => '管理费用',
            'balance_direction' => '借',
            'type' => '支出',
            'items' => [
                [
                    'number' => '520101',
                    'name' => '工资奖金',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520102',
                    'name' => '福利费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520103',
                    'name' => '社会保障费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520104',
                    'name' => '办公费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520105',
                    'name' => '水电费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520106',
                    'name' => '差旅费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520107',
                    'name' => '折旧费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520108',
                    'name' => '离退休人员工资补助',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520109',
                    'name' => '中介费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520110',
                    'name' => '应偿还受赠资产',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '520111',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5301',
            'name' => '筹资费用',
            'balance_direction' => '借',
            'type' => '支出',
            'items' => [
                [
                    'number' => '530101',
                    'name' => '借款费用',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '530102',
                    'name' => '汇兑损失',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '530103',
                    'name' => '活动费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '530104',
                    'name' => '宣传资料费',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
                [
                    'number' => '530105',
                    'name' => '其他',
                    'balance_direction' => '借',
                    'type' => '支出',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5401',
            'name' => '其他费用',
            'balance_direction' => '借',
            'type' => '支出',
            'items' => '',
        ],
    ];