<?php
return
    [
        [
            'number' => '1001',
            'name' => '库存现金',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1002',
            'name' => '银行存款',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1012',
            'name' => '其他货币资金',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1101',
            'name' => '短期投资',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1121',
            'name' => '应收票据',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1122',
            'name' => '应收账款',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1123',
            'name' => '预付账款',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1131',
            'name' => '应收股利',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1132',
            'name' => '应收利息',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1221',
            'name' => '其他应收款',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1401',
            'name' => '材料采购',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1402',
            'name' => '在途物资',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1403',
            'name' => '原材料',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1404',
            'name' => '材料成本差异',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1405',
            'name' => '库存商品',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1407',
            'name' => '商品进销差价',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1408',
            'name' => '委托加工物资',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1411',
            'name' => '周转材料',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1413',
            'name' => '低值易耗品',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1421',
            'name' => '消耗性生物资产',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1501',
            'name' => '长期债券投资',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1511',
            'name' => '长期股权投资',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1601',
            'name' => '固定资产',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1602',
            'name' => '累计折旧',
            'balance_direction' => '贷',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1604',
            'name' => '在建工程',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1605',
            'name' => '工程物资',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1606',
            'name' => '固定资产清理',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1621',
            'name' => '生产性生物资产',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1622',
            'name' => '生产性生物资产折旧',
            'balance_direction' => '贷',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1701',
            'name' => '无形资产',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1702',
            'name' => '累计摊销',
            'balance_direction' => '贷',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1801',
            'name' => '长期待摊费用',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '1901',
            'name' => '待处理财产损溢',
            'balance_direction' => '借',
            'type' => '资产类',
            'items' => '',
        ],
        [
            'number' => '2001',
            'name' => '短期借款',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => '',
        ],
        [
            'number' => '2201',
            'name' => '应付票据',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => '',
        ],
        [
            'number' => '2202',
            'name' => '应付账款',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => '',
        ],
        [
            'number' => '2203',
            'name' => '预收账款',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => '',
        ],
        [
            'number' => '2211',
            'name' => '应付职工薪酬',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => [
                [
                    'number' => '221101',
                    'name' => '职工工资',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '221102',
                    'name' => '奖金、津贴和补贴',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '221103',
                    'name' => '社会保险费',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '221104',
                    'name' => '住房公积金',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2221',
            'name' => '应交税费',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => [
                [
                    'number' => '222101',
                    'name' => '应交增值税',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => [
                        [
                            'number' => '22210101',
                            'name' => '进项税额',
                            'balance_direction' => '贷',
                            'type' => '负债类',
                            'items' => '',
                        ],
                        [
                            'number' => '22210102',
                            'name' => '销项税额',
                            'balance_direction' => '贷',
                            'type' => '负债类',
                            'items' => '',
                        ],
                        [
                            'number' => '22210103',
                            'name' => '应纳税额减征额',
                            'balance_direction' => '贷',
                            'type' => '负债类',
                            'items' => '',
                        ],
                    ],
                ],
                [
                    'number' => '222102',
                    'name' => '应交城市维护建设税',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '222103',
                    'name' => '应交教育费附加',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '222104',
                    'name' => '应交地方教育费附加',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '222105',
                    'name' => '应交企业所得税',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '222106',
                    'name' => '应交个人所得税',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '222107',
                    'name' => '应交印花税',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2231',
            'name' => '应付利息',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => '',
        ],
        [
            'number' => '2241',
            'name' => '其他应付款',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => [
                [
                    'number' => '224101',
                    'name' => '代扣社保',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
                [
                    'number' => '224102',
                    'name' => '代扣公积金',
                    'balance_direction' => '贷',
                    'type' => '负债类',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '2401',
            'name' => '递延收益',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => '',
        ],
        [
            'number' => '2501',
            'name' => '长期借款',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => '',
        ],
        [
            'number' => '2701',
            'name' => '长期应付款',
            'balance_direction' => '贷',
            'type' => '负债类',
            'items' => '',
        ],
        [
            'number' => '3001',
            'name' => '实收资本',
            'balance_direction' => '贷',
            'type' => '权益类',
            'items' => '',
        ],
        [
            'number' => '3002',
            'name' => '资本公积',
            'balance_direction' => '贷',
            'type' => '权益类',
            'items' => '',
        ],
        [
            'number' => '3101',
            'name' => '盈余公积',
            'balance_direction' => '贷',
            'type' => '权益类',
            'items' => '',
        ],
        [
            'number' => '3103',
            'name' => '本年利润',
            'balance_direction' => '贷',
            'type' => '权益类',
            'items' => '',
        ],
        [
            'number' => '3104',
            'name' => '利润分配',
            'balance_direction' => '贷',
            'type' => '权益类',
            'items' => '',
        ],
        [
            'number' => '4001',
            'name' => '生产成本',
            'balance_direction' => '借',
            'type' => '成本类',
            'items' => '',
        ],
        [
            'number' => '4002',
            'name' => '劳务成本',
            'balance_direction' => '借',
            'type' => '成本类',
            'items' => '',
        ],
        [
            'number' => '4101',
            'name' => '制造费用',
            'balance_direction' => '借',
            'type' => '成本类',
            'items' => '',
        ],
        [
            'number' => '4301',
            'name' => '研发支出',
            'balance_direction' => '借',
            'type' => '成本类',
            'items' => '',
        ],
        [
            'number' => '4401',
            'name' => '工程施工',
            'balance_direction' => '借',
            'type' => '成本类',
            'items' => '',
        ],
        [
            'number' => '4403',
            'name' => '机械作业',
            'balance_direction' => '借',
            'type' => '成本类',
            'items' => '',
        ],
        [
            'number' => '5001',
            'name' => '主营业务收入',
            'balance_direction' => '贷',
            'type' => '损益类',
            'items' => '',
        ],
        [
            'number' => '5051',
            'name' => '其他业务收入',
            'balance_direction' => '贷',
            'type' => '损益类',
            'items' => '',
        ],
        [
            'number' => '5111',
            'name' => '投资收益',
            'balance_direction' => '贷',
            'type' => '损益类',
            'items' => '',
        ],
        [
            'number' => '5301',
            'name' => '营业外收入',
            'balance_direction' => '贷',
            'type' => '损益类',
            'items' => [
                [
                    'number' => '530101',
                    'name' => '政府补助',
                    'balance_direction' => '贷',
                    'type' => '损益类',
                    'items' => [
                        [
                            'number' => '53010101',
                            'name' => '征税收入',
                            'balance_direction' => '贷',
                            'type' => '损益类',
                            'items' => '',
                        ],
                        [
                            'number' => '53010102',
                            'name' => '不征税收入',
                            'balance_direction' => '贷',
                            'type' => '损益类',
                            'items' => '',
                        ],
                    ],
                ],
            ],
        ],
        [
            'number' => '5401',
            'name' => '主营业务成本',
            'balance_direction' => '借',
            'type' => '损益类',
            'items' => '',
        ],
        [
            'number' => '5402',
            'name' => '其他业务成本',
            'balance_direction' => '借',
            'type' => '损益类',
            'items' => '',
        ],
        [
            'number' => '5403',
            'name' => '税金及附加',
            'balance_direction' => '借',
            'type' => '损益类',
            'items' => [
                [
                    'number' => '540301',
                    'name' => '城市维护建设税',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '540302',
                    'name' => '教育费附加',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '540303',
                    'name' => '地方教育费附加',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '540304',
                    'name' => '印花税',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '540305',
                    'name' => '文化事业建设费',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5601',
            'name' => '销售费用',
            'balance_direction' => '借',
            'type' => '损益类',
            'items' => '',
        ],
        [
            'number' => '5602',
            'name' => '管理费用',
            'balance_direction' => '借',
            'type' => '损益类',
            'items' => [
                [
                    'number' => '560201',
                    'name' => '工资',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '560202',
                    'name' => '办公费',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '560203',
                    'name' => '社会保险费',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '560204',
                    'name' => '住房公积金',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '560205',
                    'name' => '办公用品',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '560206',
                    'name' => '业务招待费',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5603',
            'name' => '财务费用',
            'balance_direction' => '借',
            'type' => '损益类',
            'items' => [
                [
                    'number' => '560301',
                    'name' => '银行手续费',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '560302',
                    'name' => '利息收入',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
                [
                    'number' => '560303',
                    'name' => '利息支出',
                    'balance_direction' => '借',
                    'type' => '损益类',
                    'items' => '',
                ],
            ],
        ],
        [
            'number' => '5711',
            'name' => '营业外支出',
            'balance_direction' => '借',
            'type' => '损益类',
            'items' => '',
        ],
        [
            'number' => '5801',
            'name' => '所得税费用',
            'balance_direction' => '借',
            'type' => '损益类',
            'items' => '',
        ],
    ];